/**
 * Flow phases for the questionnaire
 * Each phase represents a step in the questionnaire journey
 */
export const FLOW_PHASES = {
  MAIN: 'main',
  Q1_SELECTION: 'q1_selection',
  Q1_REVIEW: 'q1_review',
  Q1_MENTAL_HEALTH: 'q1_mental_health',
  Q2_SELECTION: 'q2_selection',
  Q2_REVIEW: 'q2_review',
  Q2_MENTAL_HEALTH: 'q2_mental_health',
  Q3_SELECTION: 'q3_selection',
  Q3_REVIEW: 'q3_review',
  Q3_MENTAL_HEALTH: 'q3_mental_health',
  SUMMARY: 'summary',
  TEAM_VISIBILITY: 'team_visibility',
  RECORD_VIDEO: 'record_video',
  RECORD_AUDIO: 'record_audio',
  RECORD_TEXT: 'record_text',
  RECORDING_COMPLETE: 'recording_complete',
  TEAM_RECORDINGS: 'team_recordings',
  MEMBER_FULL_SUMMARY: 'member_full_summary',
  COMPLETE: 'complete'
};

/**
 * Phase transitions for forward navigation
 */
export const FORWARD_TRANSITIONS = {
  [FLOW_PHASES.MAIN]: FLOW_PHASES.Q1_SELECTION,
  [FLOW_PHASES.Q1_SELECTION]: FLOW_PHASES.Q1_REVIEW,
  [FLOW_PHASES.Q1_REVIEW]: FLOW_PHASES.Q1_MENTAL_HEALTH,
  [FLOW_PHASES.Q1_MENTAL_HEALTH]: FLOW_PHASES.Q2_SELECTION,
  [FLOW_PHASES.Q2_SELECTION]: FLOW_PHASES.Q2_REVIEW,
  [FLOW_PHASES.Q2_REVIEW]: FLOW_PHASES.Q2_MENTAL_HEALTH,
  [FLOW_PHASES.Q2_MENTAL_HEALTH]: FLOW_PHASES.Q3_SELECTION,
  [FLOW_PHASES.Q3_SELECTION]: FLOW_PHASES.Q3_REVIEW,
  [FLOW_PHASES.Q3_REVIEW]: FLOW_PHASES.Q3_MENTAL_HEALTH,
  [FLOW_PHASES.Q3_MENTAL_HEALTH]: FLOW_PHASES.SUMMARY,
  [FLOW_PHASES.SUMMARY]: FLOW_PHASES.TEAM_VISIBILITY,
  [FLOW_PHASES.TEAM_VISIBILITY]: FLOW_PHASES.COMPLETE,
};

/**
 * Phase transitions for backward navigation
 */
export const BACKWARD_TRANSITIONS = {
  [FLOW_PHASES.Q1_SELECTION]: FLOW_PHASES.MAIN,
  [FLOW_PHASES.Q1_REVIEW]: FLOW_PHASES.Q1_SELECTION,
  [FLOW_PHASES.Q1_MENTAL_HEALTH]: FLOW_PHASES.Q1_REVIEW,
  [FLOW_PHASES.Q2_SELECTION]: FLOW_PHASES.Q1_SELECTION,
  [FLOW_PHASES.Q2_REVIEW]: FLOW_PHASES.Q2_SELECTION,
  [FLOW_PHASES.Q2_MENTAL_HEALTH]: FLOW_PHASES.Q2_REVIEW,
  [FLOW_PHASES.Q3_SELECTION]: FLOW_PHASES.Q2_SELECTION,
  [FLOW_PHASES.Q3_REVIEW]: FLOW_PHASES.Q3_SELECTION,
  [FLOW_PHASES.Q3_MENTAL_HEALTH]: FLOW_PHASES.Q3_REVIEW,
  [FLOW_PHASES.SUMMARY]: FLOW_PHASES.Q3_SELECTION,
  [FLOW_PHASES.TEAM_VISIBILITY]: FLOW_PHASES.SUMMARY,
};

/**
 * localStorage key for saving progress
 */
export const STORAGE_KEY = 'awfm_questionnaire_progress';
